<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="TP4VDITR-TCS019" name="tr.findlaw.tests.Sprint_18" tests="5" failures="1" timestamp="11 May 2018 12:17:52 GMT" time="921.628" errors="0">
  <testcase name="soc_4554" time="921.628" classname="tr.findlaw.tests.Sprint_18">
    <failure type="java.lang.AssertionError" message="Assertion Error!!!! Quote status is pending and not reaching Findlaw Order Tool
 java.lang.AssertionError: Quote status is pending and not reaching Findlaw Order Tool expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Error!!!! Quote status is pending and not reaching Findlaw Order Tool
 java.lang.AssertionError: Quote status is pending and not reaching Findlaw Order Tool expected [true] but found [false]
	at com.framework.reports.ReportBuilder.buildTestNodes(ReportBuilder.java:134)
	at com.framework.reports.ReportBuilder.buildReports(ReportBuilder.java:60)
	at com.framework.test.BaseTest.afterSuite(BaseTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:350)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- soc_4554 -->
  <testcase name="soc_6196" classname="tr.findlaw.tests.Sprint_18">
    <skipped/>
  </testcase> <!-- soc_6196 -->
  <testcase name="soc_6204" classname="tr.findlaw.tests.Sprint_18">
    <skipped/>
  </testcase> <!-- soc_6204 -->
  <testcase name="soc_4547" classname="tr.findlaw.tests.Sprint_18">
    <skipped/>
  </testcase> <!-- soc_4547 -->
  <testcase name="SOC_4550" classname="tr.findlaw.tests.Sprint_18">
    <skipped/>
  </testcase> <!-- SOC_4550 -->
</testsuite> <!-- tr.findlaw.tests.Sprint_18 -->
